env:
  es6: true
  node: true
  browser: true
parserOptions:
  ecmaVersion: 2018
  sourceType: module
parser: babel-eslint
extends:
  - 'eslint:recommended'
plugins:
  - 'react-hooks'
rules:
  semi:
    - 2
    - never
  no-unused-vars: 0
  no-useless-escape: 0
  no-console: 0
  quotes:
    - 2
    - single
  no-constant-condition: 0
  'react-hooks/rules-of-hooks':
    - 2
  'react-hooks/exhaustive-deps':
    - 1
