language: node_js
node_js: '11'
before_install:
- openssl aes-256-cbc -K $encrypted_7d5903de21f8_key -iv $encrypted_7d5903de21f8_iv
  -in deploy_rsa.enc -out deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 deploy_rsa
- ssh-add deploy_rsa
install:
- ssh-keyscan -t rsa -H kraftwerk28.pp.ua >> ~/.ssh/known_hosts
- cd crud
- npm i
- cd ..
- npm i
script:
- npm run build
after_success:
- git remote add deploy "kraftwerk28@kraftwerk28.pp.ua:/home/kraftwerk28/deployments/lobby2-prod"
- git config user.name "Travis CI"
- git config user.email "kefirchik3@gmail.com"kraftwerk28
- git add dist/ server/
- git commit -m "Deploy"
- git push deploy master -f
