version: '3'

services:
  app:
    build: ./
    ports:
      - 8080:80
    volumes:
      - ./data:/app/static/data
    depends_on:
      - server

  server:
    build: server/
    environment:
      NODE_ENV: 'production'
    volumes:
      - ./data:/opt/data

networks:
  default:
    external:
      name: globalpg
